### ISSUE TITLE
A problem about generation in VAE.

### ISSUE THREAD

**Issue by gcbanana** [y0ast/VAE-TensorFlow#6]
i had read your code, it is very good. But i saw that the two variables mu_encoder and logvar_encoder are both shaped [batch_size, latent_dim], if i want to generate a data, i should random a sigma, use a mu and logvar to generate, but after training we learn batch_size mus and logvars, how can i pick a mu and a logvar from them?

**Comment by y0ast** [comment]
You can pick a [1, latent_dim] for z (sample from a random distribution with mean=0 and std = 1 for best effects)
